### PR TITLE
Add tolower function in RewriteMap.

### PR DESCRIPTION
**Pull request by tgifford-webfirst**
This will allow applications to include RewriteRules that alter the path. The RewriteMap directive can not be used in .htaccess files, hence this pull request. Would you prefer to have all the internal functions mapped? See http://httpd.apache.org/docs/2.4/mod/mod_rewrite.html#rewritemap and http://httpd.apache.org/docs/2.4/rewrite/rewritemap.html#int . 

One alternative is to allow each container to customize the RewriteMap(s) for its needs using a different approach.

### CODE REVIEW

**Comment by RonWilliams** [comment]
@tgifford-webfirst Can you identify why this needs to be added to the container? What feature is dependent on the updated rewrite configuration?

**Comment by tgifford-webfirst** [comment]
This allows redirecting requests with caps to lowercase versions, e.g. /img/([^/]*)\.(JPG|PNG) -> /img/$1.${tolower:$2} (i.e. /img/something.JPG -> /img/something.jpg). That is the minimal feature we would like to provide. We can live without it, but it is a fairly minor change. The addition of toupper would probably make sense as well, but who likes shouting?

**Comment by RonWilliams** [comment]
Thank you for the additional detail. Would this break standard functionality by always redirecting requests to lowercase? I could see this potentially causing issues with sites that have files named the same, but having a different case for the file extension.

**Comment by tgifford-webfirst** [comment]
This would not break any functionality--it only allows the developer to use the tolower function in RewriteRules in their .htaccess file(s). Presumably they would take pains to make sure the RewriteRules they were adding did not cause their application to break.

```
RewriteRule ^img/.*/([^/]+)\.(jpg|jpeg|gif|png)$ /system/files/img/$1.${tolower:$2} [nocase,last,redirect=301,env=longexpiry:1]
RewriteRule ^documents/.*/([^/]+)\.(pdf|doc|docx|xls|xlsx|ppt|pptx|mp3|txt|zip)$ /system/files/documents/$1.${tolower:$2} [nocase,last,redirect=301,env=longexpiry:1]

Header always set Cache-Control "max-age=86400" env=longexpiry
# alternate cache-control for testing
Header always set Cache-Control "no-store, no-cache, must-revalidate" env=nocache
```

**Pull request merged**
